### ISSUE TITLE
Newly created cards are not added to the Recent Cards section of the launcher screen

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1002]
I can see cards created in the GitHub repo, but they are still not appearing on the Recent Cards screen. 

![image](https://user-images.githubusercontent.com/1836666/68979537-cf8b7480-07cb-11ea-8cb0-81280ca2a37a.png)

![image](https://user-images.githubusercontent.com/1836666/68979555-db773680-07cb-11ea-8784-f647f5d4c9e3.png)

**Comment by bagby** [comment]
@dnaidionov we don't have search capabilities for the new-style cards yet, we can only load cards for which we know the ID. Once we have searching we can fix this.

**Comment by jenweber** [comment]
To summarize the challenge, since cards do not share a common type, we cannot just do a search for `type: cards` like we used to. An alternative is to search for records that have an `adoptedFrom` field on them, then make requests for each card document found in those results.

This would be:
1 request for the list cards, returning n number of cards
n individual requests to get each card document

Pros:
- it works! 
- low effort

Cons:
- without auth in place for the demo app, this makes all cards visible. Including testing cards, whatever random people type in a form....
- temporary
- lots of requests done inefficiently

Another option is to use Orbit/local browser memory so that if someone makes a card, it shows up for them, but not anybody else.

**Comment by habdelra** [comment]
@jenweber one potential pitfall for option 1 is that you might run into errors where the hub doesn't know the schema for the card. In order for DocumentContext to process each record it needs to load the card schema. I'm unsure if the DocumentContext is able to discover cards' schema when dealing with a collection, as we go down a slightly different branch of logic in the DocumentContext. if you run into problems around not having schema loaded when processing a collection of cards you might want to abandon this approach.

**Comment by jenweber** [comment]
To close this ticket, we should implement option number 2.

We should consolidate the hacks into one `service` within cardhost, which we remove later. Name this service generically so it can hold other hacks too, and we keep them all in one place. Something like `interim-builder-state`.

**Comment by jenweber** [comment]
Goal:
When you visit the index page, you can see your recently created cards. Nobody else can.

To-do:
- [ ] create a service that handles browser storage in core. This is the quarantine area for temporary code.
- [ ] add a method/methods to the existing data service, which reference the browser storage service. These methods save the card id. The reason for adding it to the data service is that we want it to be available as a feature of the card model
- [ ] when a card is created, send its id to the storage 
- [ ] Add handling to make it so that the app doesn't break if the card w/ID is not found
- [ ] Add the same handling for the index (currently breaks if a requested card is missing)
- [ ] So many tests
- [ ] Add a secret query param that clears the local memory
