### ISSUE TITLE
Display Right Edge in Edit and Layout views

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1033]
-  [x] In Edit and Layout views Right Edge should be displayed all the time. 
- [ ] ~~When card is selected (no fields are in focus), Right Edge should display general card properties, all sections read-only except for Appearance.~~ needs design
- [x] Appearance section should allow a user to select a style, or edit a custom one if they have permissions. 
- [ ] ~~When a field is selected, it's edit mode related properties are displayed in the Right Edge.~~ needs design

**Comment by jenweber** [comment]
This issue has been partially resolved by PR https://github.com/cardstack/cardstack/pull/1090, because we show the right edge in layout view now, but there is still more styling and state work to do.

If anyone else wants to grab the next steps for this ticket, go for it. I am concentrating on the Themer at the moment.

**Comment by burieberry** [comment]
PR #1176 was handling this ticket along with ticket #1077 until the other ticket was blocked. I'll make #1176 to just be about this ticket so we can close it
