### ISSUE TITLE
Style system and error messages

### ISSUE THREAD

**Issue by burieberry** [cardstack/cardstack#1043]
<img width="1163" alt="system-error-messaging" src="https://user-images.githubusercontent.com/16160806/69254884-e394f480-0b84-11ea-9a8b-4dccd4547fff.png">

**Comment by jenweber** [comment]
I just merged #1136, which is the first thing that shows error messages. It had a color contrast problem, but I merged it anyway since styling is going to be handled differently here. Can you double check to make sure that whatever we land on has enough contrast? Thanks!

<img width="759" alt="Screen Shot 2020-01-06 at 2 49 43 PM" src="https://user-images.githubusercontent.com/16627268/71844778-f613b080-3094-11ea-85d4-4da64aabe698.png">
