### ISSUE TITLE
Style editor composition and styling

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1083]
Style editor (#1082, #998) has a semi-transparent background (see xd file for specs) so that when card preview size is set to full screen, user could still see the preview behind the editor. 

To close this ticket:
- [x] when the CSS editor is in focus, it gets a bright blue border. The card does NOT have such a border.
- [x] perhaps when you enter the editor, the CSS themer gets focus. Play around with this and see what works.
- [x] transparent background, #1138 

Editor window consists of two parts: CSS and HTML. 

CSS is editable, and HTML is read-only. 
When a user focuses on CSS editor, the CSS editor is highlighted. 

![image](https://user-images.githubusercontent.com/1836666/69757596-5f65e280-112b-11ea-9d52-af8548ee2990.png)
 
When a user focuses in HTML editor, it is not highlighted because the HTML is read-only

When the editor is docked on the right and preview is set to full width, we display "Hide/show editor" CTA in the top bar to toggle the editor and preview the card in full-screen width.
![image](https://user-images.githubusercontent.com/1836666/69757763-d3a08600-112b-11ea-982b-cce18f01c105.png)
![image](https://user-images.githubusercontent.com/1836666/69757773-d7340d00-112b-11ea-9f5b-bf8363c639b2.png)

XD: https://drive.google.com/open?id=1xSnis7586pGMysyWycrjvGHM7GQzbLZm
Artboard: "Motion - CSS Editor"

**Comment by jenweber** [comment]
I added visual hierarchy changes (bright blue border), but not browser/keyboard focus, since monaco has tab trapping. I think it's best to let the config buttons have focus, since ending tab trapping is somewhat hidden.

How to apply focus:
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.icodeeditor.html#focus

From [Monaco Accessibility Guide](https://github.com/Microsoft/monaco-editor/wiki/Monaco-Editor-Accessibility-Guide)

By default, pressing Tab in an editable editor inserts the Tab character (or spaces depending on the indentation setting) and does not navigate to the next focusable element on the page. You can toggle the trapping of Tab with Ctrl+M on Windows and Linux and with Ctrl+Shift+M on OSX, and subsequent Tab keys will move focus out of the editor.

You can also toggle Tab trapping from the Command Palette with the "Toggle Tab Key Moves Focus" action.
