### ISSUE TITLE
Create a URL core type

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1240]
The URL core type would be similar to case insensitive text, but will render as `href`. Links should open in a new tab. Before we have full support for card as fields we will have the value of the field serve as both display value and link URL. In the future, those two will be distinct.

**Comment by jenweber** [comment]
This work follows the patterns in #1181 

To-do:
- [ ] create `url-viewer.hbs` which is an anchor with _target="blank"
- [ ] create `url-editor.hbs` which is just the existing textfield editor
- [ ] create `url.js` which validates the entry is a string
- [ ] add core-types data to `mappings.js`
- [ ] add the new core type to the embroider config for cardhost in `ember-cli-build.js` so that it gets included in builds
- [ ] create `url-editor.js`
- [ ] add url icon to the left edge selector in schema mode
- [ ] styling
- [ ] Use the url in one of the card tests
- [ ] tests!
