### ISSUE TITLE
Create a CTA core type

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1241]
Initially, the CTA core type would be similar to case insensitive text but will render as a button. 
When rendered, field label would not be displayed, only the button itself. We will start with link buttons. A user would specify the button label and link URL. 
In the future (when we have support for cards as fields) in addition to links, we would have this type configurable to support HTTP request methods, custom actions via javascript, and cardstack action cards.

**Comment by jenweber** [comment]
This work follows the patterns in #1181 

To-do:
- [ ] create `cta-viewer.hbs` which is an anchor with _target="blank"
- [ ] create `cta-editor.hbs` which is just the existing textfield editor
- [ ] create `cta.js` which validates the entry is a string
- [ ] add core-types data to `mappings.js`
- [ ] add the new core type to the embroider config for cardhost in `ember-cli-build.js` so that it gets included in builds
- [ ] create `cta.js`
- [ ] add cta icon to the left edge selector in schema mode
- [ ] styling
- [ ] Use the cta in one of the card tests
- [ ] tests!
