### ISSUE TITLE
Actions available to users in card header

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1273]
If a user is logged in, the header would show "Edit" and contextual menu (...) buttons. 
If a user is not logged in, the header wouldn't show any buttons.
Contextual menu should contain 2 item groups: 
- Switch Mode
  - View
  - Edit 
  - Schema 
  - Preview
- Actions
  - Publish (used for sharing)
  - Save (? needs clarification)
  - Adopt (? not on a screenshot - needs clarification - creates a new card adopted from this one)
  - Copy (create a copy of a card in user's realm)
  - Archive (do not show in library, except in archived cards section)
  - Delete (delete a card. this option might be inaccessible based on some factors - e.g. permissions, existing adoption chain dependencies, etc)

![image](https://user-images.githubusercontent.com/1836666/73377090-7ee4cd00-428c-11ea-87da-1268126f48b0.png)

XD file: https://drive.google.com/open?id=1SoKB0qohhf5kBiroJbiGMGoITc4PjIMI

**Comment by jenweber** [comment]
Note to self, working off https://www.smashingmagazine.com/2017/11/building-accessible-menu-systems/ for html semantics and menu state

**Comment by jenweber** [comment]
To-do:
- [ ] button click opens context menu
- [ ] general styling so that the context menu looks like screenshot
- [ ] refactor semantics? Should these all be in one ul? Use aria labels on groups?
- [ ] clarify whether to show actions
- [ ] add functionality to the Switch mode sections
- [ ] hover item looks right
- [ ] hr looks right
- [ ] checkbox in front of active route
- [ ] checkbox is blue
- [ ] tests
- [ ] keyboard controls work
- [ ] fix z-index

**Comment by jenweber** [comment]
@dnaidionov should I hide the "actions" part of the list, or leave it in place and we gradually add functionality?

**Comment by jenweber** [comment]
Current problem:
Error: Assertion Failed: You attempted to update `contextMenuOpened` on `CardRendererHeaderComponent`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.
