### ISSUE TITLE
In Schema mode card is too narrow.

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1294]
It used to be wider, then after some update became narrower. We need to restore the initial width.

**Comment by dnaidionov** [comment]
I traced it to these lines: 
https://github.com/cardstack/cardstack/blob/449f571de55e13a24b67101bc64b640331691cc5/packages/cardhost/app/styles/components/card-renderer.css#L17-L19
Seems strange that introduction of min-width makes card narrower.

**Comment by jenweber** [comment]
The reason min-width makes it smaller is because, without this rule, it falls back to these other styles that have a larger min-width:

<img width="322" alt="Screen Shot 2020-02-03 at 11 51 22 AM" src="https://user-images.githubusercontent.com/16627268/73672825-93a1d600-467b-11ea-8127-bbab8c193200.png">
