### ISSUE TITLE
Body of the page background color should match card background on all pages

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1358]
If you scroll up or down beyond the visible page, you can get a peek of page background color, and it's not always the same. Page background color should always be the same as card's background color. We should inject the background color of currently isolated card/mode into the page. 
e.g.:
Edit mode - backgrounds match
![edit-mode-page-bg](https://user-images.githubusercontent.com/1836666/74772642-669a1980-525e-11ea-8ed4-75fc3a52ca31.gif)
View mode - page background is different from card background and is peeking when scrolling past the card (dark bars at the top/bottom)
![view-mode-page-bg](https://user-images.githubusercontent.com/1836666/74772679-79ace980-525e-11ea-91da-d4a66d6a5943.gif)

**Comment by jenweber** [comment]
We could use `overscroll-behavior` but support is not good for safari:

<img width="893" alt="Screen Shot 2020-02-24 at 4 19 22 PM" src="https://user-images.githubusercontent.com/16627268/75192028-795e9380-5721-11ea-93a1-289a7690cc83.png">

**Comment by jenweber** [comment]
Resources: 

https://www.smashingmagazine.com/2018/08/scroll-bouncing-websites/

https://stackoverflow.com/questions/8826281/disable-safari-5s-overscroll-behaviour-using-css-or-javascript

I opted for the CSS below because it seems to work across browsers. It feels a little hacky and I'm open to other approaches.

```
html {
  overflow: hidden;
}
```
