### ISSUE TITLE
Missing field icons

### ISSUE THREAD

**Issue by burieberry** [cardstack/cardstack#1474]
I don't know what we decided to do about the icons, but we should either add them, or remove the gap before the field name. Both in the card catalog menu, and in the schema field header.

<img width="1282" alt="icons" src="https://user-images.githubusercontent.com/16160806/77203138-1e248480-6ac6-11ea-8ff7-c2a184d9522b.png">

**Comment by dnaidionov** [comment]
Let's use the same icons we have now in old hub

**Comment by jenweber** [comment]
These missing icons have some code comments about needing to add them to the API.
@habdelra can you describe what you would do here? I see a few paths:

1. add a `csIcon` property to all cards, and make it a path. Put the files for our icons in public.
2. add a `csIcon` property to all cards, and make it an SVG
3. Handle it 100% in cardhost until we determine the next steps (see #1483)
4. ???

**Comment by habdelra** [comment]
@jenweber yeah when last we discussed with Chris, he said that he'd like to have a new cs field to categorize the card--so that there would be different types of card categorizations, and that the icon we display is based on the card categorization. I think, then, that means we are in a bit of a holding pattern in that we need to get some initial card categories, as well as, UI for how we want the user to assign/change a categorization on a card.

**Comment by jenweber** [comment]
Ok, in that case maybe I'll clean up my front-end-only solution so that it is acceptable to be merged, and we'll use that for now. I will also open up a new ticket that summarizes the work to be done to handle this for real.
