### ISSUE TITLE
re-running `hub:seed` results duplicate key constraint errors

### ISSUE THREAD

**Issue by habdelra** [cardstack/cardstack#161]
when hub:seed sees that a model already exists for an ID it should update the model instead of trying to create a new model with a duplicate key

**Comment by ef4** [comment]
I don't think we should expect seeds to work on an arbitrary database. It's OK to require an empty database.

Otherwise, it's very easy to end up with unpredictable state. For example: we cannot remove earlier seed data that has since been deleted from the seed files.

And seed models don't necessarily have hard-coded IDs. We can't reliably correlate them.

**Comment by habdelra** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bug: re-running hub:seed results in duplicate key constraint](https://trello.com/c/EjY3KlqF/110-bug-re-running-hubseed-results-in-duplicate-key-constraint)

**Comment by habdelra** [comment]
good point in the ID's. our particular database actually auto assigns UUID's so they should never collide if we just let the DB do its thing
