### ISSUE TITLE
Allow primary interaction with fields in edit mode

### ISSUE THREAD

**Issue by balinterdi** [cardstack/cardstack#298]
When some markup is wrapped in a `cs-field` and we're in edit mode, an overlay is rendered above the markup. That's exactly what we want in most cases, but in some cases the underlying markup has event handlers that cannot be triggered because of this.

The example where this came up is the Table of Contents for a document being wrapped in a cs-field which prevents clicking on each chapter title to load the related chapter content on the UI.

![screen shot 2018-09-17 at 10 45 44](https://user-images.githubusercontent.com/5022/45613503-e9fe7c80-ba66-11e8-8e01-786d00fac0f5.png)

To make this possible, we should mark such fields in some way (`allowHandlers`). When such a field is first interacted with in Edit mode, it should allow the interaction "to go through" (by setting `pointer-events: none` on the overlay. A subsequent 2nd click should trigger the current behavior, bringing up the editor for that field.

(See https://github.com/cardstack/deck/pull/91#issuecomment-420333736)

**Comment by balinterdi** [comment]
> To make this possible, we should mark such fields in some way (allowHandlers). When such a field is first interacted with in Edit mode, it should allow the interaction "to go through" (by setting pointer-events: none on the overlay. A subsequent 2nd click should trigger the current behavior, bringing up the editor for that field.

@ef4 Is this how we want it, or the other way around: the 1st click should focus the editor and the second, subsequent click should allow the interaction to go through?

**Comment by ef4** [comment]
When a field is selected, its overlay should either render the inline-field-editor (if there is one) or set itself to `pointer-events: none` so that the underlying content is accessible.

To make this distinction clearer, we should re-style the hover state so it has a semi-transparent background. 

An example interaction would be:

1. Hover over some content. That causes an overlay to appear, which has a semi-transparent fill making it clear that you can't (yet) interact with the content behind the overlay. (In this step, the only difference from the current behavior is the semi-transparent fill.)

2. Click on the overlay. That causes the field to be selected for editing, which does all the things it does now (like opening the field-editor on the right edge). Assume the field in question has no inline-field-editor. In that case, the overlay now becomes `pointer-events: none` so that the content is interactive.

**Comment by balinterdi** [comment]
> 1. Hover over some content. That causes an overlay to appear, which has a semi-transparent fill making it clear that you can't (yet) interact with the content behind the overlay. (In this step, the only difference from the current behavior is the semi-transparent fill.)

That would only be for fields that have no inline-field editor, right? For fields that have inline field editors, everything continues to function as currently, doesn't it?

I assume the reason is that fields *with an inline editor* should have one and only one way of interaction and that's editing their content in place.

**Comment by ef4** [comment]
Correct.

**Comment by balinterdi** [comment]
Closed via #398
