### ISSUE TITLE
CardData query and queryCard should treat `type` as optional

### ISSUE THREAD

**Issue by ef4** [cardstack/cardstack#375]
The `@cardstack/data` service has these methods:

```
  async query(type, format, opts={}) 
  async queryCard(type, format, opts={}) 
```

But `type` should really be optional here.  The query APIs are new enough that we should probably just break them to make it make more sense:

```
  async query(format, opts={}) 
  async queryCard(format, opts={}) 
```

where `type` moves into the `opts`.

In terms of implementation: heterogeneous queries are already implemented on the Hub (via `GET /api` opposed to `GET /api/${type}`). There is also already a base ember-data model named 'cardstack-card' that all the other models inherit from. Probably our Adapter should get smarter about seeing that type and changing the URL to make a heterogeneous query.

**Comment by marcoow** [comment]
I think in order to make this work with Ember Data we'd have to expose the `cardstack-card` model to the application so that Ember Data knows about that model and we can actually do `store.query('cardstack-card')`. My understanding is that we'd have to change the [code generator](https://github.com/cardstack/cardstack/blob/master/packages/models/cardstack/code-generator.js) to define a model module for `cardstack-card`.

@ef4: can you confirm that's how it's supposed to work and I'm not on the wrong track here?

**Comment by marcoow** [comment]
Hm, nevermind my above comment - `app/models/cardstack-card.js` exists already of course…
