### ISSUE TITLE
Make constraints be tied to content-type + field name

### ISSUE THREAD

**Issue by balinterdi** [cardstack/cardstack#390]
Currently, constraints are only checked against field names so if, for example, a constraint is applied to a `title` field, it will be applied to all `title` fields across all content-types (if you set up a not-null constraint for a document, it'll also apply to employees where you probably don't want it). This is counter-intuitive and the solution is to tie them to specific content-types.

**Comment by balinterdi** [comment]
@ef4 Do you think this the right approach?

**Comment by ef4** [comment]
Fields are top-level and first-class. They don't belong to a single content-type at a time. So the current behavior is intentional and consistent with everything else about fields.

That said, I agree that we need to improve the defaults here so that people aren't surprised that their fields are part of a shared namespace. That is part of a bigger design question.

Both cards and fields need to get globally-valid naming, which probably means giving them full names that include their NPM package name. We can still use shorthands that are more similar to what we have now, so that if you're in the package `@balinterdi/some-nice-card` and you define a `title` field, you're really defining the `@balinterdi/some-nice-card::title` field.

**Comment by balinterdi** [comment]
I see, all this makes sense.

The issue seems to be important to tackle, though, as fields with the same name tend to have different constraints and I'd imagine this will crop up sooner than later. We can hack around it by using unique field names (`article-title`, `employee-title`) but this will feel very artificial (`article.articleTitle`).
