### ISSUE TITLE
Editor: card search panel can never be hidden

### ISSUE THREAD

**Issue by marcoow** [cardstack/cardstack#410]
Once the card search panel comes up, there is no way to hide it again - even when leaving the edit mode, the panel does not disappear:

<img width="1200" alt="bildschirmfoto 2018-11-06 um 12 37 51" src="https://user-images.githubusercontent.com/1510/48061951-db0f8d00-e1c0-11e8-8744-1cbf2ce701d4.png">

The simplest way to fix that would be adding a _"close [x]"_ button to the top right or so. @dnaidionov did you have anything specific in mind?

### TODO

- [ ] add a _"close [x]"_ button to the card selector that closes the panel
- [ ] auto-close the card selector when the user leaves edit mode

**Comment by dnaidionov** [comment]
Close button is good. 
When user exits edit mode when the search is shown, we have another issue - the list of actions available that can be applied to the search results changes (actually, even the purpose of the search box changes), so I suggest as a simple solution we also close the search panel if user exists edit mode. If they need to search again, they will reopen search and new search panel will have the required functionality instead of adjusting on the fly.
