### ISSUE TITLE
Enable editing fields of newly added, owned record

### ISSUE THREAD

**Issue by balinterdi** [cardstack/cardstack#563]
I came across this while adding image fields to an article. When the image is added, a new File and a new Image is created and saved which works fine. However, the `alt-text` field of the image is promptly rendered in the sidebar but it is read-only because the permissions weren't fetched for it.

I added fetching the permissions for the image right after it's saved but it doesn't do anything to fix the problem as the field editors' permissions are assembled at the top (in `cs-active-composition-panel` ) and handed down to each field editor.

The field becomes editable when the whole article (the page) is reloaded.

NOTE: I'm not sure why `modelFields` is recalculated (that's why the `alt-text` field appears right away in the editor) because neither of its dependent keys (`_renderedFieldNames` and `activeContentItem.model`) changes.

**Comment by habdelra** [comment]
I've just come across what looks very similar to this but for a non-owned record. (maybe it is the same issue). In this case I can reproduce it using the @cardstack/tools dummy app. After I create a new "post" record, if I try to edit the "slug" field, I cannot because the field is disabled. 
![m1kawTl2K4](https://user-images.githubusercontent.com/61075/56300592-39dc1980-6104-11e9-901a-b662e5fa96bf.gif)
