### ISSUE TITLE
Dont display fields that are not readable in the right edge

### ISSUE THREAD

**Issue by habdelra** [cardstack/cardstack#579]
In this screenshot, the `password-hash` field is actually not readable to the user, however the right edge is leaking the existence of this field (although there is no value displayed in it, and it is not editable). We need to hide fields that are not readable in the right edge.

<img width="970" alt="screen shot 2019-01-09 at 11 21 32 am" src="https://user-images.githubusercontent.com/61075/50913314-16694a80-1402-11e9-8501-226a0aa8b06a.png">

**Comment by balinterdi** [comment]
Indeed. My only concern is there might be cases where we still want to show fields that are not editable.

A computed field that displays some useful information might be such a case, like the review status of a blog post or the number of words in a post (or comment).

Also, in some cases it might be useful for the user to see there's such a field even if they don't have permission to edit it. The review status of a blog post might be a good example, here, too. If I want to be able to change it and I see I  currently can't, it gives me a clue about how to fix that. Whereas if I don't even see it, I might be stomped about why my post doesn't appear on the blog.

I think a better way would be to add a field-level attribute (`hideInEditor`) so that it never appears in the editor.

@habdelra I now realize you didn't say we have to use `permissions` to implement this, it's just what popped into my mind as I've worked with it recently. I also think we don't currently have another method for disabling fields. We have the `disableAutoEditorFields` sledgehammer/shotgun that suppresses the rendering of all "model fields" (the ones that are not explicitly rendered in the template) but I don't think it could be used to do that.

@ef4 What do you think?

**Comment by ef4** [comment]
This is about non-readable fields, not about non-writable fields.

**Comment by balinterdi** [comment]
@ef4 Ah, I totally overlooked that, thank you.

So the implementation should be extending what we currently have in the `/permissions` response by a `readable-fields` attribute that lists all the readable fields (just like we currently do for `writable-fields`). If a field is not in `readable-fields` we shouldn't even render it.

**Comment by ef4** [comment]
Ideally, we shouldn't leak the existence of non-readable fields to the client at all. So there would be nothing to ask about. So no, I'd prefer not to make readability something clients can even ask about in the authorization API.

They're currently leaking because we don't take permissions into account when we generate the code for the ember data models. There will be ember data attrs for all fields, even ones that aren't readable. Doing this correctly involves running codegen later, and more dynamically.

If we need a quick solution, we can use the existing API for interrogating the schema. `/api/content-types/YOUR_TYPE` has a `fields` relationship, anything you can't see in there isn't something that we should render in the sidebar.

Eventually, the codegen step can happen as part of the cardstack data service when it goes to load cards. I can imagine that the spaces API request can come back with enough schema information that the client can dynamically generate the ember data models it will need to represent the cards as models.

**Comment by balinterdi** [comment]
That makes a ton of sense, thank you.

**Comment by balinterdi** [comment]
@ef4 I think there's a Catch-22 situation here, and I'd like to ask for your advice.

Over at #669 I did as you said and am now fetching the fields of the content-type we want to generate the DS.Model class for and only generate the fields which are in `relationships.fields`. 

However, that doesn't resolve the issue, because we need to pass a session object to the searchers.get for fetching the content-type, and

1) If the session is SESSION.INTERNAL_PRIVILEGED, everything works fine but we're back to square one since the almighty session can read everything.
2) If I can somehow extract/pass along the session from the request (and so the bearer token) and use that, we can't generate code for unauthenticated users.

Now that I've written this, I realize I'm probably wrong about 2). We can still generate model classes as some fields are readable for the `everyone` group and even an unauthenticated user is in that group (I think).

However, I'd still like to hear your opinion as I'm not totally sure that extracting the Bearer token, creating a session and passing it down to the codegen module is the way to go.

 And also, if 

> Eventually, the codegen step can happen as part of the cardstack data service when it goes to load cards. I can imagine that the spaces API request can come back with enough schema information that the client can dynamically generate the ember data models it will need to represent the cards as models.

on the near-term horizon, implementing what I'm working on now might be unneeded.

**Comment by balinterdi** [comment]
Update: I now make sure that the codegen plugin comes *after* authentication (it was explicitly set to come before it, not sure why), so that I have the session information I can pass to the codegen:
https://github.com/cardstack/cardstack/pull/669/commits/4e8408aa9b86abc6e615fe9797cfb32d1dc5d0a0

However, that didn't seem to make a difference. I used the `password-hash` field from the portfolio project since no read access is granted to that field (see [here](https://github.com/cardstack/portfolio/blob/53e136bf8f54bc18eb4a75fb8fd9b6acc591c05c/cards/user/cardstack/static-model.js#L31-L42)) and that was @habdelra 's original example but the searcher still returns that field for the `portfolio-users` content-type, even with an undefined session.

**Comment by balinterdi** [comment]
Also, the tests are now failing because for generating model code, we no longer use the omnipotent `Session.INTERNAL_PRIVILEGED` but using the session of the user and the `dummy/models/mock-user` module no longer seems to be generated.

**Comment by balinterdi** [comment]
@ef4 Let me put down my thoughts both as a method for clarifying them for myself and to see if my understanding and thinking are correct.

We discussed introducing a new content type, `card-definitions` that would solve two problems:

1. Prevent generating DS.Model attributes for fields that are not readable to the current user (=in the current session). The classic example is a user's password-hash field.
1. Make field ids (that are currently equal to their name) globally unique.

The mental hurdle I can't currently overcome is I don't see how introducing card-definitions (CDs) would solve the issue of getting the list of fields for the content-type that the current user is permitted to read.

I assume that CDs would somehow have a list of all fields defined for a content-type in the schema. We said that all models (of all content-types) would have a relationship link to their card-definition. 
However, how would this be better than the current (as in, this PR) solution of fetching `/content-types/:type_id` (more precisely, calling `this.searchers.get(Session.INTERNAL_PRIVILEGED, branch, 'content-types', type.id)`). If I understood correctly, the CD would contain a list of fields for the content-type but that's not unlike looping through the `fields` relationship of the search's result.

**Comment by balinterdi** [comment]
The idea I experimented with is instead of fetching the content-type to be generated and inspect its `fields` relationship (since that contains all fields, irrespective of session information), to try to fetch *all fields* of the content-type individually and only generate DS.attrs for the ones we can fetch:

```js
async _generatedModel(modelName, type, branch, session) {
  let fields = []
  for (let field of [...type.realAndComputedFields.values()]) {
    if (field.id === 'id' || field.id === 'type') {
      continue;
    }
    try {
      await this.searchers.get(session, branch, 'fields', field.id);
      fields.push(field);
    } catch (error) {
      if (error.isCardstackError) {
        continue;
      }
      throw error;
    }
  };
  return modelTemplate({
    modelName,
    fields,
    routingField: type.routingField
  });
}
```

The problem with this is that depending on what session information we pass, we either get too much or too little. `Session.EVERYONE` can't access any fields (unless we explicitly give EVERYONE read access for fields we want to be generate), while `Session.INTERNAL_PRIVILEGED` can access all fields, including the ones that are not readable for anyone (e.g `password_hash`).

Even if we could somehow get a session that generates DS.attrs for fields that EVERYONE can read, there is the further problem of possibly needing to refresh the generated model classes once the session is updated (most often, when the user logs in).

@ef4 What do you think about having a field attribute that would instruct the code generator not to generate a DS.attr for the field (`shouldGenerateAttr`)?

**Comment by ef4** [comment]
I don't think this is the direction we want to go long term, and as you pointed out there is already a short-term workaround for this issue.

**Comment by balinterdi** [comment]
I'm probably not shooting high enough but the only issues I see with the content-types' current schema is what I'd described above:

> 1. Prevent generating DS.Model attributes for fields that are not readable to the current user (=in the current session). The classic example is a user's password-hash field.
> 1. Make field ids (that are currently equal to their name) globally unique.

In order to allow these, I don't think the following modifications would be sufficient:

1. Add a `serverOnlyFields` to the schema definition:

```js
factory.addResource('content-types', 'portfolio-users')
  .withRelated('fields', [
    factory.addResource('fields', 'email-address').withAttributes({
      fieldType: '@cardstack/core-types::case-insensitive'
    }),
    factory.addResource('fields', 'password-hash').withAttributes({
      fieldType: '@cardstack/core-types::string'
    }),
    factory.addResource('fields', 'name').withAttributes({
      fieldType: '@cardstack/core-types::string'
    }),
    factory.addResource('fields', 'avatar-url').withAttributes({
      fieldType: '@cardstack/core-types::string'
    }),
  ])
  .withRelated('server-only-fields', [
    factory.getResource('fields', 'password-hash')
  ]);
```

When generating attributes for the DS.Model of the content-type, it would be enough to remove the fields that are in the `server-only-fields` relationship.

2. Currently the `withRelated` method in the `jsonapi-factory` is extremely simple. We use the dasherized form of the passed field ids in the `withRelated` list and create fields from those. That potentially leads to naming conflicts when a field is fetched by its id, for example, when adding constraints (there can be several fields with the same id, like `title`).

To prevent that, we could include the resource type when creating the field, to make it unique:

```js
class ResourceFactory {
  (...)
  withRelated(fieldName, value) {
    if (!value) {
      throw new Error(`No value for ${fieldName}`);
    }
    if (!this.data.relationships) {
        this.data.relationships = {};
    }
    let data;
    if (Array.isArray(value)) {
      data = value.map(entry => ({ type: entry.type, id: `${entry.type}::${entry.id}` }));
    } else {
      data ={ type: value.type, id: `${value.type}::${value.id}` };
    }
    this.data.relationships[dasherize(fieldName)] = { data };
    return this;
  }
}
```

We'd then have to take care that when a field is accessed by its id, we prefix it with the content-type's type, as shown above.

### What this design doesn't do

* It can't create different DS attributes based on the context (for example, it can't include password hash in certain contexts and not in others).

### Further considerations

* The question of when to load the schema (and to generate the code)  for a specific card (= content-type) seems independent from what that schema should look like. From what I understand, `code-generators` are cardstack plugins that are run at boot-up time. It's this process that'd need to be more dynamic and pull-based so that code generators only run when they need to.
