### ISSUE TITLE
Github Torii config mismatch

### ISSUE THREAD

**Issue by courajs** [cardstack/cardstack#6]
The github login component currently doesn't work, because it writes config to the torii provider [`github-oauth2` here][with-o], but attempts to use the unconfigured [`github` here][without-o].

[with-o]: https://github.com/cardstack/cardstack/blob/8fc22b3fa875caaeff4887e4e9344ec7ac0e3b98/packages/github-auth/addon/components/github-login.js#L22
[without-o]: https://github.com/cardstack/cardstack/blob/8fc22b3fa875caaeff4887e4e9344ec7ac0e3b98/packages/github-auth/addon/components/github-login.js#L35

**Comment by ef4** [comment]
Thanks. This was working for me because the app I was testing within happened to have its own provider named 'github' that just extended the github-oauth2 one.

**Comment by ef4** [comment]
(There's not test suite coverage for github-auth, I'm not clear on exactly how we'd want to do that.)

**Comment by ef4** [comment]
By the way: github-auth does essentially work. But there are some caveats/notes:

1. We don't have any automatic model generation or plugin-provided schema yet, so you need to establish your own model to represent users. The out-of-the-box behavior of the github-auth plugin is to need a model with type "github-users". This can be customized by setting a userTemplate on your authentication-source (which lets you alter how github's users get rewritten to local users). The default user template in github-auth itself can serve as a starting point.

2. github-auth includes a Searcher that will provide read-only models with type "github-users" by getting them directly from GitHub. This is useful if you want to outsource all user data to GitHub. If instead you just want to use GitHub for authentication and then establish local user accounts that you will store in your own data-sources, that is also possible -- you would make a user model with a different type than "github-users" and configure 

3. I haven't implemented groups yet in github-auth, which will be the best way to tie users to grants with permissions to do things.

4. We don't have read authentication at all at the moment, so you can't really use github-auth in production, because the authentication-source itself (which needs to store the client secret) can be read via jsonapi.
