### ISSUE TITLE
Improve handling of (conflicting) global field names

### ISSUE THREAD

**Issue by marcoow** [cardstack/cardstack#617]
The fact that fields are global in cardstack is (while not necessarily a problem as such) something that is relatively surprising when you're new to the framework. Since conflicting fields also don't raise an error (or warning even) but would just silently not do what you'd expect makes it super easy to accidentally define conflicting fields without recognizing. I think we should just raise an error in these cases.

**Comment by ef4** [comment]
There are multiple interacting layers of problem here.

I am 100% agreed that we should be causing fields to be namespaced per package by default. This involves promoting both fields and content-types to being "features", in the same way that a writer or middleware is a feature, since features have a well-constructed global namespace involving NPM package names.

Erroring instead for now would be nice, except it's complicated by another problem, which is the way we're handling per-card-package schema. Right now the most common pattern is to use the static-models feature. This isn't really what that feature was designed for, and it's not really appropriate to error during indexing of data sources (that is basically too late for the person composing a site to do anything about the error).

Finally, there is a missing chunk of design work around how the "card" and "data source" concepts truly relate at scale, once you have many of both from different authors.

I think a short-term thing you can do is add a test to your card monorepo that loads all the static-model.js files for the cards and verifies no duplicates.
