### ISSUE TITLE
cardstack-session.user errors if authentication fails

### ISSUE THREAD

**Issue by courajs** [cardstack/cardstack#7]
[`cardstack-session.js:20`][js] calls `pushPayload` with whatever comes back from the authentication request. This will create a user model if it succeeds, but it throws an error for a failure response. The particular failure payload I'm getting is:
```json
{
  "errors": [{
      "title": "OK",
      "detail": "incorrect_client_credentials",
      "code": 200
    }]
}
```

[js]: https://github.com/cardstack/cardstack/blob/8fc22b3fa875caaeff4887e4e9344ec7ac0e3b98/packages/authentication/addon/services/cardstack-session.js#L20

**Comment by ef4** [comment]
Thanks.

The root cause here is that the authentication request is returning a status 200 even though it failed. Most likely this is because the github API is also returning a 200 for an error response. 

The place to catch this would be either [here](https://github.com/cardstack/cardstack/blob/4b395ef50a90906a6e6c00b7e7b00002857ccadf/packages/github-auth/cardstack/authenticator.js#L35) or [here](https://github.com/cardstack/cardstack/blob/4b395ef50a90906a6e6c00b7e7b00002857ccadf/packages/github-auth/cardstack/authenticator.js#L54)
