### ISSUE TITLE
Generate an application adapter that the other adapters extend

### ISSUE THREAD

**Issue by marcoow** [cardstack/cardstack#717]
The `@cardstack/models` package currently [generates one adapter per model](https://github.com/cardstack/cardstack/blob/master/packages/models/cardstack/code-generator.js#L107) which is good as it provides flexibility so that things can be overridden on a per-model basis. However, as all these adapters are re-exports of the `@cardstack/models/adapter` adapter which cannot be overridden in the app, it is impossible to override anything for **all** models without having to override that thing for each model individually (by actually creating all these files in `app/adapters`). That also means of course that any time a new model is added, a new adapter has to be added in the app as well as otherwise that particular override would not be active for that new model leading to potentially broken behavior of the app.

It'd be easier if one `application` adapter would be generated so that that would be the central point where the app could override things for **all** models at once. Of course it would still be possible to define certain things on a per-model-basis by creating the respective file. I'm not sure why all these adapters are generated in the first place though as they are all the same anyway?

**Comment by balinterdi** [comment]
Adding to that, the current thinking (dare I call it, best practice) about adapters and serializers is that there should only be a single application adapter (and serializer) and all logic should go inside there. 

runspired thinks this is really important one of the main reasons being that adapters (and serializers) are usually *API* and not type dependent. Since he's one of the architects of ED, we'll probably see the pruning of most hooks and even the deprecation of type-specific adapters.

**Comment by habdelra** [comment]
How about the `cardstack-card` adaptor? I’m believe all models actually extend this.

**Comment by ef4** [comment]
I don't consider this area high priority, because ember-data itself should be an internal implementation detail that cards can't even observe.

(We're also about to change it all, given hassan's work on model encapsulation.)
