### ISSUE TITLE
Should we yield raw model value in block form for cs-field?

### ISSUE THREAD

**Issue by venkatd** [cardstack/cardstack#76]
https://github.com/cardstack/cardstack/blob/efdffedaa63394ce9313c0891d6464055c3544d2/packages/tools/addon/templates/components/cs-field.hbs#L4

When I used the block form I was expecting to get the raw value passed along. What is your thinking of passing along `{{yield (get content fieldName)}}` instead of the value which could potentially include a placeholder?

**Comment by ef4** [comment]
Substituting the placeholder is deliberate. We don't want every template author to need to think about placeholders. Rather they should be thinking about how to render the full range of values that are possible for the field.

For example, a date field might get rendered like:

```hbs
{{#cs-field content "dueDate" as |date|}}
  {{#if (date-is-valid date) }}
     <span>{{moment-format date format="mm/dd/yy"}}</span>
  {{else}}
     <span class="missing-date">mm/dd/yy</span>
   {{/if}}
{{/cs-field}}
```

Since this example already does something sensible for null dates, you could configure the placeholder value of that field-type to be `null` (instead of the default, which would be the string "Enter due date").

**Comment by ef4** [comment]
For an example of a field-type that customizes its placeholder value, see [the mobiledoc package here](https://github.com/cardstack/cardstack/blob/b927dde2f6379e69ba0b4cc34ddc47b9c4e0e40f/packages/mobiledoc/app/field-types/mobiledoc.js#L5-L8).

**Comment by ef4** [comment]
Oh, and that linked example also shows how to customize `isEmpty`, which determined whether to show a placeholder at all. You could also just override that so that the framework never considers the field empty and therefore never shows a placeholder value.

**Comment by venkatd** [comment]
Ok all is clear. I should be customizing the placeholder to be `null` and handle that appropriate. Thanks for the explanation :)
