### ISSUE TITLE
Add CLI commands and functionality to render a card in isolation

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#782]
- [ ] `cardstack start` starts docker containers and the hub. The hub uses a git repo in the homedir as its default data source
- [x] `cardstack pre-build` uses the blueprint to create an app environment #799 
- [x] `cardstack new my-card-name` generates `components/embedded[.js, .hbs. css]` and isolated
- [ ] `cardstack play .` in a directory adds the card definition as a data source in the hub, and prints a URL that shows the card definition in action
    - [ ] add the generated files into a real build in temp (synthesize entry points in `app/card.js` that is a list of files with full paths, `Users/name/homedir/...`. We will not copy files in. Requires work in embroider to let us use dynamic variables in the import statements. See https://github.com/embroider-build/embroider/issues/198
    - [ ] make sure file watching happens - might work through webpack in embroider
    - [ ] create a route (via query param `?isolate=your-card`) for showing a card in isolation (isolated = essentially an interactive preview pane)
    - [ ] start the local server

**Comment by jenweber** [comment]
## Bookmarked features

Ideas for what the CLI should do, that we aren't doing now
- validate card name

**Comment by jenweber** [comment]
Needs research:

- [ ] is the deprecation bug fixed?
- [ ] what does webpack watch and how can we configure it? Or do we need to watch in Broccoli?
- [ ] where do we define data sources?

**Comment by ef4** [comment]
I resolved one of the research items above: webpack's watching mode *does* follow newly introduced directories at runtime. Meaning when somebody runs `cardstack play` to send a new card into the running system, it's enough for us to synthesize the right `import` statements, and any changes to that card's code will cause a rebuild.

This means we should change embroider so that instead of telling webpack when to build, we turn webpack's watching on and have it watch the output of embroider stage2 (in addition to everything else, like cards that it discovers elsewhere on disk).

**Comment by jenweber** [comment]
obsolete with new-hub
