### ISSUE TITLE
Use embedded code editor to display card model

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#950]

**Comment by habdelra** [comment]
@burieberry this is the requirement that I was mentioning around showing the card document (for which we are hiding the code block)

**Comment by jenweber** [comment]
Work is tracked on `json-viewer`.

<img width="1564" alt="Screen Shot 2019-11-06 at 7 27 37 PM" src="https://user-images.githubusercontent.com/16627268/68349549-88b2c600-00cb-11ea-9d27-ba8d262ee279.png">

Webpack config was no fun at all. It's best to not pass any options into the plugin.

Getting this to work took a fix to `css-loader` version update to embroider: https://github.com/embroider-build/embroider/pull/351 because of [this bug](https://github.com/css-modules/postcss-modules-scope/pull/3)

Also `requirejs.s` in the monaco loader clashes with Ember's requirejs. One way to fix this is to create a package whose job it is to make sure the key exists. In `SimpleWorker.js` of monaco-editor, this is the problem line: ` loaderConfiguration = self.requirejs.s.contexts._.config;`

**Comment by jenweber** [comment]
Closed, we hide this now, and it uses monaco
