### ISSUE TITLE
Solidify cross-datasource schema usage

### ISSUE THREAD

**Issue by courajs** [cardstack/cardstack#96]
Once the hub is up and running, and the index is fully populated, any data source can reference data or schema from any other data source. But during the initial indexing, errors can pop up due to load order.

When models from one data source try to reference schema from a datasource that hasn't yet been indexed, `readOtherIndexers` for the schema model can return undefined, and we'll see some error like this:
```
cardstack/indexers Unexpected error in _updateLoop Error: field "user" refers to missing related type "mock-users"
```

Here's an example of a seed file that can break it: https://github.com/cardstack/cardstack/blob/ad1344592a77b91b8ed8d963bf5e8d8e8d584446/packages/notification/tests/dummy/cardstack/seeds/development/ephemeral.js

You can check out that commit (ad1344592a77b91b8ed8d963bf5e8d8e8d584446), and run `ember serve` inside the notification package to reproduce.

We should probably do some more lightweight discovery of all the data sources before trying to validate a complete schema.

**Comment by ef4** [comment]
This happens because at each stage in the indexing process, we are discovering the schema from the current set of indexers, and that schema may include more data sources, which causes us to do another stage and discover yet more schema.

At each stage, we construct a fully-valid schema, which is where we hit these validation errors.

The alternative is to just manually keep searching for data sources without constructing intermediate schemas. Should be possible.

**Comment by courajs** [comment]
@ef4 This happens even if all data sources are specified in the seed data: https://github.com/cardstack/cardstack/blob/7a31970849a454e840c18bafa2c1d55d48e2a308/packages/notification/tests/dummy/cardstack/seeds/development/ephemeral.js

**Comment by courajs** [comment]
Oh - but I guess the seed data is an indexer now - I hadn't really internalized that.

**Comment by ef4** [comment]
well, it's an indexer that's available immediately on the first pass, so that does seem like it would work.
